STA-17 Вёрстка страницы логина
ShamilSaifotdinov/bugs-survivors pull request #10
Opened 2024-05-03 12:32 UTC by Lestrous

STA-17 Вёрстка страницы логина

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/47781960/6e9d86d8-68ca-44ac-abf1-cc70d99ceead)

2024-05-06 15:26 UTC, ShamilSaifotdinov requested changes
Необходимо обновиться (смержить в свою ветку новое состояние main). А так замечаний нет.

2024-05-15 14:46 UTC, ShamilSaifotdinov requested changes

2024-05-15 14:46 UTC, ShamilSaifotdinov commented on packages/client/src/mui-workplace-preset.tsx
> +          // lineHeight: '1.4rem',
Лучше убрать неиспользуемый код

2024-05-15 14:46 UTC, ShamilSaifotdinov commented on packages/client/src/mui-workplace-preset.tsx
> +          // lineHeight: '1.4rem',
Лучше убрать неиспользуемый код

2024-05-15 14:46 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Login/index.tsx
> +              label="Password"
Так как это ввод пароля - необходимо добавить type="password" для скрытия вводимого значения

2024-05-15 14:46 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Login/index.tsx
> +      .catch(err => console.log(err))
Ошибки надо выводить в интерфейс (например через helperText в TextField)

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/3d3687b5-0a7c-46d7-aa6e-450c5e6c94a1)

2024-05-16 17:05 UTC, ShamilSaifotdinov approved these changes

2024-05-16 17:26 UTC, merged

2024-05-16 18:49 UTC, kyzinatra commented
К сожалению не смогу проверить смерженый pull request. Откатите изменения и откройте pull request для ревью снова. Можно уже не ждать апрува от коллег и отправить так.