Sta 36 верстка страницы пользователя
ShamilSaifotdinov/bugs-survivors pull request #13
Opened 2024-05-06 08:15 UTC by Aptyaa

### Какую задачу решаем
Верстка страницы профиля (без логики)

### Скриншоты/видяшка (если есть)
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/74553411/a9c0250d-d6aa-4f33-8e35-1379c4bef335)

### TBD (если есть)

2024-05-06 16:53 UTC, ShamilSaifotdinov requested changes

2024-05-06 16:53 UTC, ShamilSaifotdinov commented on packages/client/src/pages/registration/RegisterPage.tsx
Необходимо удалить из данной ветки, так как уже есть в main

2024-05-06 16:53 UTC, ShamilSaifotdinov commented on packages/client/src/pages/registration/styles.module.scss
Необходимо удалить из данной ветки, так как уже есть в main

2024-05-06 16:53 UTC, ShamilSaifotdinov commented on packages/client/src/router.tsx
> +import RegisterPage from './pages/registration/RegisterPage'
Необходимо убрать добавление RegisterPage, так как уже есть в ветки main

2024-05-06 16:53 UTC, ShamilSaifotdinov commented on packages/client/src/mui-workplace-preset.tsx
Все изменения, кроме MuiAvatar, уже есть в main. Необходимо убрать данные изменения и обновить свою ветку.

2024-05-06 16:53 UTC, ShamilSaifotdinov commented on packages/client/src/main.tsx
Все изменения уже есть в main. Необходимо убрать данные изменения и обновить свою ветку.

2024-05-06 16:53 UTC, ShamilSaifotdinov commented on packages/client/src/components/AvatarLoad/AvatarLoad.tsx
> +            Загружай аватарку
Игру договорились делать на английском языке

2024-05-06 16:53 UTC, ShamilSaifotdinov commented on packages/client/src/components/AvatarLoad/AvatarLoad.tsx
> +            Пока ветер без камней :)
Игру договорились делать на английском языке

2024-05-06 16:53 UTC, ShamilSaifotdinov commented on packages/client/src/components/AvatarLoad/AvatarLoad.tsx
> +          <Input
Лучше заменить на https://mui.com/material-ui/react-button/#file-upload

2024-05-06 16:53 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Profile/ProfilePage.tsx
> +                  {changePass ? (
Лучше сделать смену пароля в модальном окне

2024-05-06 16:53 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Profile/ProfilePage.tsx
> +          <Grid item xs={8}>
Не хватает кнопки возврата в главное меню

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/e3050a5e-13cc-49b5-bcae-0c00aac0a004)

2024-05-07 07:18 UTC, Aptyaa commented on packages/client/src/pages/Profile/ProfilePage.tsx
> +                  {changePass ? (
Почему?

2024-05-08 15:35 UTC, ShamilSaifotdinov requested changes

2024-05-08 15:35 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Profile/ProfilePage.tsx
> +                            CHANGE AVATAR
Должно быть Change password

2024-05-08 17:39 UTC, ShamilSaifotdinov approved these changes

2024-05-08 17:44 UTC, merged