Sta 33 подключить api для смены аватара
ShamilSaifotdinov/bugs-survivors pull request #21
Opened 2024-05-13 13:39 UTC by Aptyaa

### Какую задачу решаем
Подключить API для смены аватара

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-05-15 07:45 UTC, kyzinatra commented
К сожалению без ревью от коллег не смогу проверить вашу работу. Пригласите их для проверки, после апрува отправьте работу снова

2024-05-15 07:47 UTC, ShamilSaifotdinov requested changes

2024-05-15 07:47 UTC, ShamilSaifotdinov commented on packages/client/src/components/AvatarLoad/AvatarLoad.tsx
>    className?: any
Тип "any" лучше заменить на "unknown" (или учитывая, что это class css, то на string)

2024-05-15 07:47 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Profile/index.tsx
Лучше как с Password, все, что связано с Avatar вынести в отдельную папку

2024-05-15 07:47 UTC, ShamilSaifotdinov commented on packages/client/src/components/AvatarLoad/AvatarLoad.tsx
>  function AvatarLoad({ src, className, onChange }: AvatarLoadProps) {
Необходимо переделать работу с src, так как происходит пустой запрос к https://ya-praktikum.tech/api/v2/resources перед получением данных профиля

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/d1d0b70f-efdd-434a-836b-694a0224882e)

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/a6e01336-157c-4346-b031-c542f8f9b009)

RESOURCES_URL лучше перенести в AvatarLoad и только при не пустом profile.avatar делать полную ссылку
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/7129884f-54a9-47fb-905d-444ada1dbfd3)

2024-05-15 07:47 UTC, ShamilSaifotdinov commented on packages/client/src/components/AvatarLoad/AvatarLoad.tsx
> +      <VisuallyHiddenInput onChange={onChange} type="file" />
Добавь accept="image/*", чтобы только картинки можно было выбирать

2024-05-18 12:35 UTC, ShamilSaifotdinov approved these changes

2024-05-18 13:56 UTC, kate-lozovaya requested changes
Оставила комментарии, посмотри их и призывай к ревью

2024-05-18 13:56 UTC, kate-lozovaya commented on packages/client/src/components/AvatarLoad/AvatarLoad.tsx
> +  const handleAvatar = async (e: React.ChangeEvent<HTMLInputElement>) => {
[Исправление]
Стоит обернуть в `useCallback`, чтобы функция не пересоздавалась на ререндеры

2024-05-18 13:56 UTC, kate-lozovaya commented on packages/client/src/components/AvatarLoad/AvatarLoad.tsx
> +          avatar ? `${RESOURCES_URL}${avatar}` : 'images/defaultAvatar.png'
[Предложение]
Лучше вынести 'images/defaultAvatar.png' в константу, чтобы можно было ее легко найти поиском по коду и поменять при необходимости

2024-05-18 13:56 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/index.tsx
> +                src={profile.avatar as string}
[Вопрос - Исправление]
А какой еще может быть тип у `profile.avatar`, что его нужно переводить как `as string`?
`as string` просто выключает проверку typescript, лучше проверить значение, и, если он `undefined`, то можно заменять на пустую строку значение или не показывать `AvatarLoad`

2024-05-18 13:56 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/index.tsx
>                  className={styles.avatar}></AvatarLoad>
[Исправление]
Здесь не нужен закрывающий тег, его лучше убрать. И можно настроить линтер так, чтобы закрывающий тег автоматически убирался, если в компоненте нет `children`

2024-05-22 07:09 UTC, kate-lozovaya commented
Привет!
Переведи в системе практикума еще задачу на меня, у меня сейчас нет кнопки взять в работу

2024-05-22 07:29 UTC, kate-lozovaya requested changes
Оставила комментарии
Ответь на них, пожалуйста. Потом призывай к ревью и переводи на меня задачку в практикуме

2024-05-22 07:29 UTC, kate-lozovaya commented on packages/client/src/components/AvatarLoad/AvatarLoad.tsx
> +  const defaultAvatar = 'images/defaultAvatar.png'
[Исправление]
Константу лучше вынести за пределы компонента, чтобы она не пересоздавалась на ререндеры. 
И ее надо перевести в кейс констант. Или ЗАГЛАВНЫМИ_БУКВАМИ, или PascalCase, в зависимости от того, как в проекте их записываете

2024-05-22 07:29 UTC, kate-lozovaya commented on packages/client/src/components/AvatarLoad/AvatarLoad.tsx
> +    []
[Вопрос - Предложение - Исправление]
А тут точно не должно быть никаких зависимостей? Есть ли в проекте `eslint` правило `react-hooks/exhaustive-deps`, которые создает варнинги на отсутствие зависимостей?

2024-05-22 07:29 UTC, kate-lozovaya commented on packages/client/src/components/AvatarLoad/AvatarLoad.tsx
> +        src={avatar ? `${RESOURCES_URL}${avatar}` : defaultAvatar}></Avatar>
[Исправление]
Тут не нужен закрывающий тег `</Avatar>`

Можно добавить правило линтера, которое будет закрывать теги автоматически
```
"react/self-closing-comp": [
  "error",
  {
    "component": true,
    "html": true
  }
],
```

2024-05-22 07:29 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/index.tsx
> +                src={profile.avatar as string}
Тут не исправлено и нет комментария. Напишешь, с какими сложностями сталкиваешься, если убрать `as string`?

2024-05-22 07:29 UTC, kate-lozovaya commented on packages/client/src/components/AvatarLoad/AvatarLoad.tsx
> +        src={avatar ? `${RESOURCES_URL}${avatar}` : defaultAvatar}></Avatar>
[Предложение]
Еще сразу при первом ревью не заметила, поэтому просто как предложение. 

Можно вынести `avatar ? \`${RESOURCES_URL}${avatar}\` : defaultAvatar` в отдельную функцию `getAvatarSrc` в `utils` (или ваш аналог в проекте). Тогда можно будет переиспользовать этот кусочек кода, если понадобится. 

```ts
const DEFAULT_AVATAR = 'images/defaultAvatar.png'

function getAvatarSrc(avatar?: string) {
  return avatar ? `${RESOURCES_URL}${avatar}` : DEFAULT_AVATAR
}
```

2024-05-22 11:33 UTC, Aptyaa commented on packages/client/src/pages/Profile/index.tsx
> +                src={profile.avatar as string}
Тип может быть unknown из-за типизации useValidationForm : 
**export const useValidationForm = (
  data: Record<string, unknown> & (Partial<User> | SignInData | SignUpData)
) => {...}**
TS ругался поэтому привел к string

2024-05-22 11:37 UTC, Aptyaa commented on packages/client/src/components/AvatarLoad/AvatarLoad.tsx
> +    []
У нас набор правил 
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/74553411/4f4e6e48-4da5-4766-9123-de77d37a1632)
Ну когда линтер запускаю, на пустую зависимость он не ругается. Да я и не совсем понимаю, какая тут нужна зависимость , по сути функция остается же одна и таже. Я пытался в профайлере смотреть на скорость рендера с юзколбеком и без, разницы особо не заметил. Не знаю есть ли смысл вообще в такой оптимизации

2024-05-22 11:41 UTC, Aptyaa commented on packages/client/src/components/AvatarLoad/AvatarLoad.tsx
> +  const defaultAvatar = 'images/defaultAvatar.png'
исправил

2024-05-22 11:41 UTC, Aptyaa commented on packages/client/src/components/AvatarLoad/AvatarLoad.tsx
> +        src={avatar ? `${RESOURCES_URL}${avatar}` : defaultAvatar}></Avatar>
испраивл

2024-05-22 11:42 UTC, Aptyaa commented on packages/client/src/components/AvatarLoad/AvatarLoad.tsx
> +        src={avatar ? `${RESOURCES_URL}${avatar}` : defaultAvatar}></Avatar>
исправил

2024-05-22 11:48 UTC, kate-lozovaya commented on packages/client/src/components/AvatarLoad/AvatarLoad.tsx
> +    []
это правило `react-hooks/exhaustive-deps` надо в `rule` записывать

2024-05-22 11:52 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/index.tsx
> +                src={profile.avatar as string}
Выше предложила варианты для исправления

2024-05-22 11:54 UTC, kate-lozovaya reviewed
Вместо `as string` можно использовать `?? ''`, если пустая строка тоже будет валидной. Либо показывать `AvatarLoad`, только если есть `profile.avatar` - `{profile.avatar && <AvatarLoad ... />}`

2024-05-22 14:39 UTC, Aptyaa commented on packages/client/src/pages/Profile/index.tsx
> +                src={profile.avatar as string}
При другом варианте у меня все равно появляются ошибки.
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/74553411/ff920333-fc67-4a76-870c-5bd1a1730a2c)
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/74553411/304ae427-0f96-48b8-9d2a-92261da0ae54)
Я не знаю как от них избавиться, не переделывая тип в useFormValidation о котором я выше написал

2024-05-22 15:15 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/index.tsx
> +                src={profile.avatar as string}
Можно проверять тогда `typeof profile.avatar === 'string'`. Если это тоже не получится, можешь оставить так, как есть

2024-05-22 20:30 UTC, Aptyaa commented on packages/client/src/pages/Profile/index.tsx
> +                src={profile.avatar as string}
Так работает. Сделал такую проверку внутри src, так как по умолчанию аватар приходит пустой строкой с сервера для нового пользователя, и если не отображать дефолтный аватар, его нельзя будет поменять

2024-05-23 17:31 UTC, kate-lozovaya approved these changes
👍🏻

2024-05-24 17:15 UTC, merged