Andreyshulga333/sta 43: Реализовать начало и окончание игры
ShamilSaifotdinov/bugs-survivors pull request #33
Opened 2024-05-20 18:36 UTC by etacarinae333

Реализовал начало и окончание игры, показываю результаты.
Пофиксил таймер (при переходе на другую вкладку игра застывала, а таймер продолжал тикать)

2024-05-20 23:59 UTC, ShamilSaifotdinov requested changes

2024-05-20 23:59 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Discovery/index.tsx
Папку "Discovery" необходимо удалить, так как уже есть main menu

2024-05-20 23:59 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Game/index.tsx
> +let timer = 0
Таймер лучше исправить позже, так как в другом PR уже есть исправления связанные с таймером

2024-05-20 23:59 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Game/index.tsx
> +  Bullets: Bullets
Классы лучше не переносить

2024-05-20 23:59 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Game/index.tsx
> +    this.navigate = navigate
Лучше заменить на
`constructor(..., public navigate: NavigateFunction) {
...(без добавления this.navigate = navigate)
}`

2024-05-20 23:59 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Game/index.tsx
> +    useEffect(() => {
Не желательно использовать useEffect в данном классе

Исправления, с init лучше оставить на позже, так как часть изменений уже есть в другом PR

2024-05-20 23:59 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Game/index.tsx
> +    useEffect(() => {
\+ все подобные исправления ниже сейчас создают баг связанный с ускорением у пользователей, у которых монитор больше 60fps

2024-05-21 00:10 UTC, etacarinae333 commented on packages/client/src/pages/Game/index.tsx
> +  Bullets: Bullets
аннотация типов должна быть сверху. Я просто перенес наверх

2024-05-21 00:10 UTC, etacarinae333 commented on packages/client/src/pages/Game/index.tsx
> +let timer = 0
мне таймер нужен был для отображения результатов на странице окончания игры

2024-05-21 00:49 UTC, ShamilSaifotdinov approved these changes

2024-05-21 07:29 UTC, kyzinatra commented on packages/client/src/pages/Game/index.tsx
> +    useEffect(() => {
Про нежелательность `useEffect` абсолютно согласен. Может вызвать кучу проблем. + Тут требуется очистка при `unmount`

2024-05-21 07:29 UTC, kyzinatra commented on packages/client/src/pages/Game/index.tsx
> +      lastTimerUpdate = now
Магические числа лучше вынести в отдельные константы и использовать их везде

2024-05-21 07:31 UTC, kyzinatra commented
Вы отлично постарались! Хочу также похвалить ваших коллег за отличное ревью. Посмотрите их и мои комментарии, чтобы сделать вашу работу еще лучше. Ваши достижения в этом проекте показывают, как много вы уже узнали и применили на практике.

2024-05-21 09:48 UTC, merged