Andreyshulga333/sta 53: Тесты на игру и на страницу регистрации
ShamilSaifotdinov/bugs-survivors pull request #35
Opened 2024-05-21 16:59 UTC by etacarinae333

Тестируем игру и страницу регистрации

2024-05-23 09:40 UTC, npb73 commented on packages/client/src/pages/GamePage/Game/Bullets.ts
> +      }
Неверно изменен код логики flameThrow. При наличии этой сопосбности пули появляются каждый игровой тик.

2024-05-23 11:00 UTC, ShamilSaifotdinov requested changes

2024-05-23 11:00 UTC, ShamilSaifotdinov commented on packages/client/src/pages/GamePage/Game/Bullets.ts
> +        this.state.push({
FlameThrow (огнемет) стал менее эпичней

Раньше:
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/e666aa01-778b-4405-8298-89d20645d62b)

Сейчас
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/018443a4-fcf1-440a-aa37-23d2a27b3f2b)

2024-05-27 16:51 UTC, npb73 approved these changes

2024-05-28 06:06 UTC, ShamilSaifotdinov approved these changes

2024-05-28 06:06 UTC, merged