STA-56 Добавить OAuth-авторизацию в проект
ShamilSaifotdinov/bugs-survivors pull request #43
Opened 2024-06-02 14:14 UTC by Lestrous

STA-56 Добавить OAuth-авторизацию в проект

2024-06-02 21:03 UTC, ShamilSaifotdinov requested changes

2024-06-02 21:03 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Login/index.tsx
> +              Авторизоваться через Яндекс
Как минимум, нужно на английском, но лучше заменить на иконку

Из [макета в Figma](https://www.figma.com/design/dYLs3teXU4A5MqlxKg5Cur/Bugs-Survivors?node-id=0-1&t=G6UF0lWwnITVqyPT-1) ([сама иконка](https://yastatic.net/s3/home-static/_/Z/6/nfVezDRqofwQZ5e669DSK84Tw.svg)):
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/260f1dc7-add2-41df-887f-98c51e927ab8)

2024-06-02 21:03 UTC, ShamilSaifotdinov commented on packages/client/src/pages/MainMenu/index.tsx
> +    typeof window !== 'undefined'
Надо добавить комментарий, что необходимо **убрать проверку после совмещения SSR и Redux**

2024-06-02 21:03 UTC, ShamilSaifotdinov commented on packages/client/src/store/slices/userSlice.ts
> +    return response
Здесь нет смысла что-то возвращать в случае успеха

2024-06-02 21:03 UTC, ShamilSaifotdinov commented on packages/client/src/store/slices/userSlice.ts
> +  unknown,
Так как нечего возвращать - заменить на undefined

2024-06-02 21:03 UTC, ShamilSaifotdinov commented on packages/client/src/store/slices/userSlice.ts
> +        .addCase(logOutUser.fulfilled, (state, action) => {
action не используется, можно удалить

2024-06-02 21:03 UTC, ShamilSaifotdinov commented on packages/client/src/store/slices/userSlice.ts
> +    id: 0,
Лучше заменить на null, так как потенциально id: 0 может быть

2024-06-02 21:03 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Login/index.tsx
> +            id: 0,
Лучше заменить на null, так как потенциально id: 0 может быть

2024-06-02 21:03 UTC, ShamilSaifotdinov commented on packages/client/src/pages/registration/Registration.test.tsx
> +jest.mock('../../hooks/useLoggedInUser', () => ({
Добавить описание выше (как и у других моков) в духе "// Мокаем проверку авторизованности пользователя"

2024-06-02 21:03 UTC, ShamilSaifotdinov commented on packages/client/src/hooks/useLoggedInUser.ts
> -          location.pathname !== '/signup' &&
Из-за удаление данной проверки невозможно открыть регистрацию (происходит переход
 на авторизацию)

2024-06-02 21:03 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Login/index.tsx
> +  }, [navigate, user.status, user.user.id])
user.status и user.user.id можно заменить на user

2024-06-03 16:51 UTC, Lestrous commented on packages/client/src/store/slices/userSlice.ts
> +    id: 0,
По типам может быть number | undefined, заменил на undefined

2024-06-03 17:29 UTC, ShamilSaifotdinov approved these changes

2024-06-03 20:13 UTC, kyzinatra commented on packages/client/src/pages/Login/index.tsx
> +    typeof window !== 'undefined'
Обязательно стоит убрать. Тем более условный хук

2024-06-03 20:13 UTC, kyzinatra commented on packages/client/src/pages/Login/index.tsx
> +      return
Классное решение, как сократить условие

2024-06-03 20:14 UTC, kyzinatra commented on packages/client/src/pages/Login/index.tsx
> +      })
URI стоит вынести в отдельную константу

2024-06-03 20:14 UTC, kyzinatra commented on packages/client/src/pages/Login/index.tsx
> +              variant="contained"
По аналогии тут. Стоит сменить `redirect_uri` на общую константу

2024-06-03 20:16 UTC, kyzinatra approved these changes
В целом все сделано хорошо. Вы отлично потрудились. Из моментов, которые можно улучшить могу посоветовать вынести в отдельные константы все url. Так их проще будет менять. К примеру при деплое

2024-06-04 05:06 UTC, merged