STA-58 Добавить FullScreen API
ShamilSaifotdinov/bugs-survivors pull request #44
Opened 2024-06-04 11:20 UTC by Aptyaa

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-06-04 19:09 UTC, ShamilSaifotdinov requested changes
Необходимо добавить автоматический выход из полноэкранного режимы при окончании игры или при выходе из игры

2024-06-04 19:09 UTC, ShamilSaifotdinov commented on packages/client/src/pages/GamePage/index.tsx
>    useEffect(() => {
Необходимо оставить отступ между объявлением констант и useEffect для читаемости

2024-06-04 19:09 UTC, ShamilSaifotdinov commented on packages/client/src/pages/GamePage/index.tsx
> -
Необходимо оставить отступ для читаемости

2024-06-06 17:49 UTC, Aptyaa commented on packages/client/src/pages/GamePage/index.tsx
> -
done

2024-06-06 17:49 UTC, Aptyaa commented on packages/client/src/pages/GamePage/index.tsx
>    useEffect(() => {
done

2024-06-06 20:59 UTC, ShamilSaifotdinov approved these changes

2024-06-06 20:59 UTC, ShamilSaifotdinov commented on yarn.lock
Необходимо удалить из репо (git rm --cached yarn.lock)

2024-06-06 20:59 UTC, ShamilSaifotdinov commented on packages/client/src/hooks/useFullScreen.ts
> +      document.exitFullscreen()
При запуске игры возникает ошибка

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/2dc42d38-7a9a-444a-9ec8-ba2ad949b779)

2024-06-07 16:00 UTC, Aptyaa commented on yarn.lock
done

2024-06-07 16:01 UTC, Aptyaa commented on packages/client/src/hooks/useFullScreen.ts
> +      document.exitFullscreen()
done

2024-06-07 17:36 UTC, kyzinatra commented on packages/client/src/hooks/useFullScreen.ts
> +      document.mozCancelFullScreen()
Эту функцию лучше вынести в `utils`

2024-06-07 17:36 UTC, kyzinatra commented on packages/client/src/hooks/useFullScreen.ts
> +      document.documentElement.requestFullscreen()
По аналогии

2024-06-07 17:37 UTC, kyzinatra commented on packages/client/src/hooks/useFullScreen.ts
> +      !document.msFullscreenElement
По аналогии лучше абстрагироваться от конкретных условий и просто вызывать `isFullscreen()` к примеру

2024-06-07 17:38 UTC, kyzinatra commented
Отличная работа! Хоть изменений и не много, но все они сделаны хорошо. Вы отлитчно внедрили fullscreen api. Так держать

2024-06-08 16:43 UTC, merged