STA-55
ShamilSaifotdinov/bugs-survivors pull request #45
Opened 2024-06-04 16:36 UTC by etacarinae333

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-06-04 22:00 UTC, ShamilSaifotdinov requested changes
В файл src/pages/Login/index.tsx необходимо добавить в проверку "rejected", так как на клиенте теперь отсутствует пустое начальное состояние

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/d14deb74-dd19-4847-a8dc-d3aa9c3bbb5e)

2024-06-04 22:00 UTC, ShamilSaifotdinov commented on .gitignore
> +yarn.lock
Так как файл вносится в .gitignore - то необходимо сам файл удалить из репозитория (https://stackoverflow.com/questions/2047465/how-do-i-delete-a-file-from-a-git-repository)

2024-06-04 22:00 UTC, ShamilSaifotdinov commented on packages/client/package.json
> +    "cookie-parser": "^1.4.6",
Необходимо также добавить @types/cookie-parser для typescript

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/9602b817-4e75-4b44-b618-20ac126113c9)

2024-06-04 22:00 UTC, ShamilSaifotdinov commented on packages/client/src/entry-server.tsx
> +    console.log(routes, url, foundRoutes, fetchData)
console.log лучше убрать

2024-06-04 22:00 UTC, ShamilSaifotdinov commented on packages/client/src/store/index.ts
> +    typeof window === 'undefined' ? undefined : window.APP_INITIAL_STATE,
Необходимо добавить в src/type.d.ts:
```
declare global {
  interface Window {
    APP_INITIAL_STATE: RootState
  }
}

export {}
```

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/d7989322-bcda-4c91-9421-7ccb4365768e)

2024-06-04 22:00 UTC, ShamilSaifotdinov commented on .env.sample
> +INTERNAL_SERVER_URL=http://server:3002
Необходимо добавить пробел в конце файла

2024-06-04 22:00 UTC, ShamilSaifotdinov commented on packages/client/src/entry-server.tsx
> +  ] = foundRoutes
Лучше убрать переносы и сделать в одну строку

2024-06-05 11:38 UTC, ShamilSaifotdinov requested changes

2024-06-05 11:38 UTC, ShamilSaifotdinov commented on packages/client/src/client.d.ts
Ошибка не ушла

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/ef7fff4f-5c08-45e2-a97c-12bd9c040379)

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/6d552202-ca4a-4afa-a273-e98b801b82e8)

2024-06-05 12:38 UTC, ShamilSaifotdinov approved these changes

2024-06-05 17:08 UTC, kyzinatra commented
Отличная работа! Хорошее подключение SSR с Redux. Вопросов к работе у меня нет. 
Вы отлично потрудились!

2024-06-05 18:24 UTC, merged