STA-71: Setup docker (Postgresql, pgadmin, server,client)
ShamilSaifotdinov/bugs-survivors pull request #46
Opened 2024-06-13 15:25 UTC by etacarinae333

STA-71: Setup docker (Postgresql, pgadmin, server,client).
.env file was changed

Containers run on URIs below:
Client: http://localhost:3000
Server: http://localhost:3001
Postgresql: http://localhost:5432

2024-06-13 21:04 UTC, ShamilSaifotdinov requested changes

2024-06-13 21:04 UTC, ShamilSaifotdinov commented on mongo/WiredTiger
Как минимум, папка mongo должна быть в gitignore.
Как максимум, mongo вообще не должно быть, так как нигде не будет применятся

2024-06-13 21:04 UTC, ShamilSaifotdinov commented on README.md
Данные пробелы не имеют смысла

2024-06-13 21:04 UTC, ShamilSaifotdinov commented on packages/client/package.json
> +    "build": "tsc --project tsconfig.server.json && vite build --ssr src/entry-server.tsx --outDir dist/server",
Первый vite build необходим для сборки клиент, второй для сервера ssr

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/a3165729-7ea5-4f50-8419-774852e097b6)

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/6766c5d4-c932-4b34-9a7a-f0bc1c5e6199)

2024-06-13 21:04 UTC, ShamilSaifotdinov commented on docker-compose.yml
> +  pgadmin:
pgAdmin на проде не нужен (желательно установить локально)

2024-06-13 21:04 UTC, ShamilSaifotdinov commented on docker-compose.yml
> +      - '${CLIENT_PORT}:80'
Внутренний порт сейчас не 80, а 3000

2024-06-13 21:04 UTC, ShamilSaifotdinov commented on docker-compose.yml
> +      - mongo
client нужно запускать после server (depends_on: server) или независимо

2024-06-13 21:04 UTC, ShamilSaifotdinov commented on docker-compose.yml
Необходимо восстановить порядок следования сервисов для читаемости изменений в коде

2024-06-13 21:04 UTC, ShamilSaifotdinov commented on docker-compose.yml
> +    environment:
Необходимо заменить на env_file: - ./.env

2024-06-13 21:04 UTC, ShamilSaifotdinov commented on docker-compose.yml
> +      SERVER_PORT: ${SERVER_PORT}
Необходимо добавить "networks: - awesome" для работы внутри своей сети

2024-06-13 21:04 UTC, ShamilSaifotdinov commented on packages/server/package.json
> +    "http": "^0.0.1-security",
Данные зависимости не используются на сервере

2024-06-13 21:04 UTC, ShamilSaifotdinov commented on packages/server/index.ts
> +  return users
Для проверки соединения с СУБД без создания таблиц можно вставить такой запрос:

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/8d2093e1-3b8b-4842-b20e-4308b973a773)

2024-06-13 21:04 UTC, ShamilSaifotdinov commented on packages/server/postgres.ts
> +  host: HOST,
Для использования в локальной сети хостовой машины - заменить на наименование сервиса ("postgres")

2024-06-13 21:04 UTC, ShamilSaifotdinov commented on packages/server/tsconfig.prod.json
> +  "extends": "./tsconfig.json",
В данном изменении нет смысла

2024-06-13 21:04 UTC, ShamilSaifotdinov commented on packages/server/index.ts
> +dotenv.config({ path: '../../.env' })
Не желательно использовать относительные пути (при сборки контейнера файлы меняют свое положение). Данное уточнение не влияет на работу - можно удалить

2024-06-14 05:42 UTC, ShamilSaifotdinov requested changes

2024-06-14 05:42 UTC, ShamilSaifotdinov commented on README.md
Неисправлено

2024-06-14 05:42 UTC, ShamilSaifotdinov commented on packages/server/package.json
> +    "mongodb": "^6.7.0",
Неактуально. Удалить

2024-06-14 05:42 UTC, ShamilSaifotdinov commented on docker-compose.yml
> +      - postgres
Postgres уже будет запущен перед сервером. Удалить

2024-06-14 05:45 UTC, ShamilSaifotdinov approved these changes

2024-06-14 11:41 UTC, ShamilSaifotdinov commented on docker-compose.yml
> +    image: prackicum-server
Не актуально - можно удалить

2024-06-14 11:41 UTC, ShamilSaifotdinov commented on docker-compose.yml
> +    image: prakticum-client
Не актуально - можно удалить

2024-06-14 12:12 UTC, etacarinae333 commented on README.md
это преттиер поправил

2024-06-14 12:44 UTC, ShamilSaifotdinov commented on README.md
Окей

2024-06-14 13:00 UTC, kyzinatra approved these changes
По работу замечаний у меня нет. Подключение реализовано хорошо

2024-06-14 13:04 UTC, merged