Sta 25 Верстка страницы регистрации
ShamilSaifotdinov/bugs-survivors pull request #5
Opened 2024-04-25 21:09 UTC by Aptyaa

### Какую задачу решаем
Верстка страницы регистрации

### Скриншоты/видяшка (если есть)
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/74553411/cdaf6953-4c64-48f4-bc7c-2e5a6c80618a)

### TBD (если есть)

2024-04-26 07:32 UTC, ShamilSaifotdinov requested changes
Необходимо обновить ветку (сделать merge с main и устранить конфликты с приоритетом к ветки main)

2024-04-26 08:09 UTC, ShamilSaifotdinov requested changes

2024-04-26 08:09 UTC, ShamilSaifotdinov commented on packages/client/src/pages/registration/RegisterPage.tsx
> +              placeholder="Second name"></TextField>
Необходимо placeholder заменить на label и привести стилю

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/8b2704ed-5531-486b-92ff-587345172512)

2024-04-26 08:09 UTC, ShamilSaifotdinov commented on packages/client/src/pages/registration/RegisterPage.tsx
> +            <ButtonGroup
ButtonGroup лучше заменить на обычный div, так как теряются скругления

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/e6ffe1fa-ccc6-4e6d-a326-3e113cd8d830)

2024-04-26 08:09 UTC, ShamilSaifotdinov commented on packages/client/src/App.tsx
> +        contrastText: 'black',
black лучше заменить на Blue Dianne/900 (#2F464A)
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/9895f9d3-7e46-4bd4-b591-8f83ea4cad7b)

2024-04-26 08:09 UTC, ShamilSaifotdinov commented on packages/client/src/pages/registration/RegisterPage.tsx
> +              <Button variant="contained" color="secondary">
Неверный цвет текста

2024-04-30 18:31 UTC, ShamilSaifotdinov requested changes

2024-04-30 18:31 UTC, ShamilSaifotdinov commented on lerna-debug.log
Надо удалить этот файл

2024-04-30 18:31 UTC, ShamilSaifotdinov commented on packages/client/index.html
> +    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
Ранее был добавлен фавикон. Надо его оставить.

2024-04-30 18:31 UTC, ShamilSaifotdinov commented on packages/client/src/App.tsx
> -
Лучше оставить отделение импортов от кода

2024-04-30 18:31 UTC, ShamilSaifotdinov commented on packages/client/src/main.tsx
> +const theme = createTheme({
themeOptions был вынесен в отдельный файл ./mui-workplace-preset. Необходимо оставить в отдельном файле и обновить под свой код.

2024-04-30 18:31 UTC, ShamilSaifotdinov commented on packages/client/src/assets/images/BugsSurvivorsBGt.png
Изображения должны храниться в папке public/images.

2024-04-30 18:31 UTC, ShamilSaifotdinov commented on packages/client/src/pages/registration/styles.module.scss
> +  background-image: url('../../assets/images/BugsSurvivorsBGt.png');
Необходимо обновить на '/images/{наименование файла}.{расширение}'

2024-05-01 19:05 UTC, ShamilSaifotdinov requested changes
Необходимо добавить роут

2024-05-01 19:05 UTC, ShamilSaifotdinov commented on packages/client/src/pages/registration/styles.module.scss
> +  background-image: url('/images/BugsSurvivorsBGt.png');
Надо добавить "image-rendering: pixelated;", так как картинка сейчас отображается смазанной

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/3e81840b-e88d-4db6-9a92-1b08d9a54f9e)

2024-05-01 19:05 UTC, ShamilSaifotdinov commented on packages/client/index.html
> +
Лучше не вносить изменения, не имеющие смысла.

2024-05-01 19:05 UTC, ShamilSaifotdinov commented on packages/client/src/pages/registration/RegisterPage.tsx
> +          backgroundColor: '#2F464AB2',
Стилизацию лучше делать в styles.module.scss через индивидуальные классы

2024-05-01 19:05 UTC, ShamilSaifotdinov commented on packages/client/src/pages/registration/RegisterPage.tsx
> +            </Typography>
Обрезается часть наименования (см. замечание mui-workplace-preset.tsx про lineHeight)

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/a1ad3866-0c19-452e-81e6-44b7b8df1353)

2024-05-01 19:05 UTC, ShamilSaifotdinov commented on packages/client/src/pages/registration/RegisterPage.tsx
> +          display: 'flex',
Зачем использовать компоненты grid, если по итогу используются flexbox?
Если не получается кастомизировать уже имеющийся компонент - лучше обойтись div с прописанными стилями в style.module.scss

2024-05-01 19:05 UTC, ShamilSaifotdinov commented on packages/client/src/pages/registration/RegisterPage.tsx
> +                  justifyContent={'space-between'}>
Надо добавить gap, чтобы кнопки не слипались

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/6a8ca1e6-ed03-4389-94ea-fffff2fc2e2d)

2024-05-01 19:05 UTC, ShamilSaifotdinov commented on packages/client/src/mui-workplace-preset.tsx
> +    MuiButton: {
Кастомизовать кнопки не имеет смысла, так как в макете используются кнопки из MUI.
Лучше у кнопок добавить "variant="contained""

2024-05-01 19:05 UTC, ShamilSaifotdinov commented on packages/client/src/mui-workplace-preset.tsx
> +      lineHeight: '4.9rem',
lineHeight не может быть меньше fontSize

2024-05-01 19:05 UTC, ShamilSaifotdinov commented on packages/client/src/mui-workplace-preset.tsx
> +      defaultProps: {
Прорефакторить, так как влияет на отображение на других страницах

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/9ac8c849-1c27-4258-aa93-87cfeb610b97)

2024-05-01 19:05 UTC, ShamilSaifotdinov commented on packages/client/src/mui-workplace-preset.tsx
> +      textAlign: 'center',
Лучше убрать, так как не везде используется center

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/cec1162a-fb7b-4566-ac74-6a1e39be2a2f)

2024-05-01 19:28 UTC, Aptyaa commented on packages/client/index.html
> +
А я хз как это происходит вообще))

2024-05-03 06:49 UTC, ShamilSaifotdinov requested changes

2024-05-03 06:49 UTC, ShamilSaifotdinov commented on packages/client/src/App.css
Пустой неиспользуемый файл - надо удалить

2024-05-03 06:49 UTC, ShamilSaifotdinov commented on packages/client/src/main.tsx
> +import './index.css'
index.css пустой, поэтому лучше удалить строку и файл

2024-05-03 06:49 UTC, ShamilSaifotdinov commented on packages/client/src/pages/registration/RegisterPage.tsx
> +        <Grid container justifyContent={'center'}>
Добавь "height={'100%'} alignItems={'center'}"

В данный момент так (поля ввода не по вертикальному центру):
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/317d7310-610f-4140-94e2-2535d070ded4)

2024-05-03 06:49 UTC, ShamilSaifotdinov commented on packages/client/src/mui-workplace-preset.tsx
> +          border: '1px solid #C1E0DF',
Получились квадратные текстовые поля.
"border: '1px solid #C1E0DF'," лучше убрать

В данный момент:
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/80c76640-9904-43a5-8155-fdd7733602af)

2024-05-03 06:49 UTC, ShamilSaifotdinov commented on packages/client/src/mui-workplace-preset.tsx
> +          backgroundColor: '#FFFFFF',
Получились квадратные текстовые поля.
"backgroundColor: '#FFFFFF'," лучше перенести в MuiInputBase

В данный момент:
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/80c76640-9904-43a5-8155-fdd7733602af)

2024-05-03 06:49 UTC, ShamilSaifotdinov commented on packages/client/src/mui-workplace-preset.tsx
> +      lineHeight: '5.5rem',
lineHeight: '5.5rem', надо убрать - влияет на другие верстки

2024-05-03 06:49 UTC, ShamilSaifotdinov commented on packages/client/src/mui-workplace-preset.tsx
> +      lineHeight: '2.5rem',
lineHeight: '2.5rem', надо убрать - влияет на другие верстки

2024-05-03 06:49 UTC, ShamilSaifotdinov commented on packages/client/src/mui-workplace-preset.tsx
> +      textAlign: 'center',
textAlign: 'center', надо убрать - влияет на другие верстки

2024-05-03 08:30 UTC, etacarinae333 commented on packages/client/src/pages/registration/RegisterPage.tsx
> +
Перепиши пожалуйста на try catch
const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    try {
      e.preventDefault()
      const response = await fetch(`${BASE_URL}/auth/signup`, {
        method: 'POST',
        body: JSON.stringify(dataForm),
        headers: {
          'Content-Type': 'application/json',
        },
      })
      if (!response.ok) {
        throw new Error(`Network response with status ${response.status}`)
      }
      setDataForm(initialData)
      navigate('/signin')
    } catch (error) {
      console.log(error)
    }
  }
  Сейчас promises никто не юзает, try catch Более читаемый

2024-05-03 08:30 UTC, etacarinae333 commented on packages/client/src/mui-workplace-preset.tsx
> +      lineHeight: '2.5rem',
Лучше в процентах задать line-height: 140% например, тогда будет высчитываться от размера шрифта текущего елемента

2024-05-03 08:30 UTC, etacarinae333 commented on packages/client/src/mui-workplace-preset.tsx
> +          fontFamily: 'Roboto, sans-serif',
Мы используем только  Montserrat и Press Start 2P

2024-05-04 16:22 UTC, Aptyaa commented on packages/client/src/mui-workplace-preset.tsx
> +          fontFamily: 'Roboto, sans-serif',
а это тогда что 
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/74553411/9d29f232-f773-45d1-920b-3fb74d9e1ce1)

2024-05-04 16:22 UTC, Aptyaa commented on packages/client/src/mui-workplace-preset.tsx
> +          backgroundColor: '#FFFFFF',
если я перенесу будет вот так 
![Uploading image.png…]()

2024-05-04 16:50 UTC, Aptyaa commented on packages/client/src/pages/registration/RegisterPage.tsx
> +
ok

2024-05-04 21:22 UTC, ShamilSaifotdinov commented on packages/client/src/mui-workplace-preset.tsx
> +          fontFamily: 'Roboto, sans-serif',
Это из стандартно mui, можно игнорировать

2024-05-04 21:39 UTC, ShamilSaifotdinov requested changes

2024-05-04 21:39 UTC, ShamilSaifotdinov commented on packages/client/src/pages/registration/RegisterPage.tsx
> +        <Grid container justifyContent={'center'}>
align-content видимо не во всех браузерах поддерживается корректно

Яндекс браузер:
![7073ea2e-1cab-422e-bed6-2178d630b558](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/66893b7a-888c-4345-8d1b-d456ad41043c)

Google Chrome:
![c75183e3-2e7d-4ba0-8122-608902f16fbc](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/8ff9e84f-0d1a-4656-85c1-4e3ce6c120ea)

![12f1ef78-5b76-42d9-a165-8ddfd08897cd](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/2319117f-b653-427b-b8e3-d34770fe61a9)

2024-05-05 11:07 UTC, etacarinae333 approved these changes

2024-05-06 15:18 UTC, ShamilSaifotdinov approved these changes

2024-05-06 15:18 UTC, merged