STA-90 Поддержать API форума на клиенте
ShamilSaifotdinov/bugs-survivors pull request #50
Opened 2024-06-22 18:46 UTC by Lestrous

STA-90 Поддержать API форума на клиенте

2024-06-23 01:03 UTC, ShamilSaifotdinov requested changes

2024-06-23 01:03 UTC, ShamilSaifotdinov commented on packages/client/src/api/basic/forum.ts
> +    `/topic/${topicId}/comments?offset=${offset}&limit=${limit}`
"?offset=${offset}&limit=${limit}" лучше напрямую не прописывать, а использовать queryString (уже есть в в fetchApi/get, необходимо передать в option.data)

2024-06-23 01:03 UTC, ShamilSaifotdinov commented on packages/client/src/api/basic/forum.ts
> +}
Все типы лучше вынести в отдельный файл (из за чего сам форум и типы можно вложить в папку forum, а forum.ts переименовать в index.ts)

2024-06-23 01:03 UTC, ShamilSaifotdinov commented on packages/client/src/api/basic/forum.ts
> +    }`
"?offset=${offset}&limit=${limit}${replyId ? \`&replyId=${replyId}\` : '' }" лучше напрямую не прописывать, а использовать queryString (уже есть в в fetchApi/get, необходимо передать в option.data)

2024-06-23 01:03 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumSubjectTable/index.tsx
> +        <meta name="description" content={'Форум'} />
Заголовок и content везде указывается по английски

2024-06-23 01:03 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumSubjectTable/index.tsx
> +            src={item.creator.avatar}
В данный момент сохраняется относительная ссылка, а не абсолютная, поэтому нужно использовать helper/getAvatarSrc

2024-06-23 01:03 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumTopicCommentTable/index.tsx
> +            src={item.creator.avatar}
В данный момент сохраняется относительная ссылка, а не абсолютная, поэтому нужно использовать helper/getAvatarSrc

2024-06-23 01:03 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumSubjectTable/index.tsx
> +          <TableRow
Лучше вынести в отдельный файл

2024-06-23 01:03 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumSubjectTable/index.tsx
>          <ButtonModal
Лучше вынести в отдельный файл (окно с созданием темы)

2024-06-23 01:03 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumSubjectTable/index.tsx
Переименовать папку ForumSubjectTable в ForumTable

2024-06-23 01:03 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumTopicTable/index.tsx
> +  const handleCreateComment = () => {
Вынести в отдельный файл (вмести с полем ввода и кнопками)

2024-06-23 01:03 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumTopicCommentTable/index.tsx
> +) {
Вынести в отдельный файл

2024-06-23 01:03 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumSubjectTable/index.tsx
>              </Button>
Если тема с таким наименованием уже существует - необходимо выводить ошибку

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/d6c40dd6-f4e2-4070-bdfa-d434e430bb2b)

2024-06-23 01:32 UTC, ShamilSaifotdinov requested changes

2024-06-23 01:32 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumTopicTable/index.tsx
Дизайн не соответствует макету (как минимум поле ввода должен соответствовать своему уровню вложенности, а то не понятно для какого уровня пишется ответ, необходим больше отступ для разных уровней вложенности)

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/3fcefc61-79a8-49c3-9fe1-6f44b6386791)

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/24b89b99-39f9-4fe2-835e-2c00df603a35)

2024-06-24 04:37 UTC, ShamilSaifotdinov requested changes
Привести папки, файлы и **наименование переменных** к виду:

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/b38d3ef2-e19b-484b-98e8-2326c2ce762e)

Подобные переменные читать сложно:

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/60d25a99-c641-4baa-84fa-e486c9ed02a8)

2024-06-24 04:37 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumTable/ForumTableRow.tsx
> +  return getTableRowsData(data).map(row => {
Обернуть в `<>{...}</>`, так как сейчас пишет ошибку:

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/4b309af6-d980-43f5-a6c4-34259f535338)

А вообще необходимо было вынести строку (Row), а не цикл

2024-06-24 04:37 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumTable/ForumTableRow.tsx
> +        {forumSubjectColumns.map(column => {
Убрать слово Subject отовсюду

2024-06-24 04:37 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumTopicTable/ForumTopicTableRow.tsx
> +  return getTableRowsData(data).map(row => (
Обернуть в `<>{...}</>`, так как сейчас пишет ошибку:

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/3266b200-77b8-411f-97aa-cc5144494f8e)

А вообще необходимо было вынести строку (Row), а не цикл

2024-06-24 04:37 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumTopicCommentTable/ForumTopicCommentTableRow.tsx
> +  return getTableTopicCommentRowsData(data, nestingLevel).map(row => (
Обернуть в `<>{...}</>`, так как сейчас пишет ошибку:

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/ca618737-6b67-4f1b-a118-c2347a350643)

2024-06-24 04:37 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumSubjectTable/index.tsx
>          <ButtonModal
Не решено

2024-06-24 18:34 UTC, ShamilSaifotdinov approved these changes

2024-06-25 00:56 UTC, kyzinatra commented on packages/client/src/api/basic/basicInstance.ts
>  export const gameInstance = fetchApi('https://ya-praktikum.tech/game/api/v2')
Константы url лучше выносить отдельно

2024-06-25 00:58 UTC, kyzinatra commented on packages/client/src/pages/Forum/Table/CreateTopicModal/index.tsx
> +  }
Здорово, что вы обрабатываете ошибки

2024-06-25 01:01 UTC, kyzinatra reviewed
Отличная работа! Особенно хочу снова похвалить ваших коллег за отличное ревью, нечнго даже добавить. Все сделано отлично! Вы отлично потрудились и ваша работа принята! Желаю успехов в дальнейшем обучении

2024-06-25 01:01 UTC, kyzinatra approved these changes

2024-06-25 02:26 UTC, merged