leaderboard
ShamilSaifotdinov/bugs-survivors pull request #55
Opened 2024-06-25 18:03 UTC by npb73

### Какую задачу решаем
Создание лидерборда
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/48920818/ccee05ef-b47f-4b28-8c2e-7b14ac4b898c)

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-06-25 19:00 UTC, ShamilSaifotdinov requested changes

2024-06-25 19:00 UTC, ShamilSaifotdinov commented on packages/client/src/api/basic/leaderboard.ts
> +export type Data = {
Типы необходимо вынести в types и наименование должно быть более конкретное

2024-06-25 19:00 UTC, ShamilSaifotdinov commented on packages/client/src/pages/GameOver/index.tsx
> +      ratingFieldName: 'score',
Лучше заменить на seconds

2024-06-25 19:00 UTC, ShamilSaifotdinov commented on packages/client/src/api/basic/leaderboard.ts
> +}
Лучше привести к виду:
```suggestion
  export type LeaderboardPostData = {
    score: number
    seconds: number
    user: LeaderboardUserData
  }
  export type LeaderboardUserData ={
    id: number
    login: string
    avatar?: string
  }
```

2024-06-25 19:00 UTC, ShamilSaifotdinov commented on packages/client/src/pages/GameOver/index.tsx
> +        name: user?.user?.display_name,
Лучше использовать - он всегда будет

2024-06-25 19:00 UTC, ShamilSaifotdinov commented on packages/client/src/pages/GameOver/index.tsx
> +    leaderboardPost({
Добавить проверку на авторизованность (наличия user)
При отсутствии user - post не выполняется

2024-06-25 19:00 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Leaderboard/components/LeaderboardTable/index.tsx
> +          src={item.user.avatar}
Необходимо использовать getAvatarSrc

2024-06-25 19:00 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Leaderboard/components/LeaderboardTable/index.tsx
> +      const filteredData = leaderboardResponse.filter(
Убрать фильтрацию

2024-06-25 19:00 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Leaderboard/components/LeaderboardTable/index.tsx
> +          name: item.data.name!,
Должен быть логин

2024-06-25 19:00 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Leaderboard/components/LeaderboardTable/index.tsx
> +          id: item.data.user_id!.toString(),
Не приводить к строке

2024-06-25 19:00 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Leaderboard/components/LeaderboardTable/index.tsx
> +          avatar: '/images/defaultAvatar.png', // Default avatar, replace with actual if available
Аватар по умолчанию итак есть в Avatar. Транслировать из пришедших данных

2024-06-25 19:00 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Leaderboard/components/LeaderboardTable/index.tsx
> +        score: item.data.score!,
При отсутствии item.data.score - ставить 0

2024-06-25 19:00 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Leaderboard/components/LeaderboardTable/index.tsx
> +      const leaderboardResponse = response as LeaderboardResponse // Type assertion
Вместо "as LeaderboardResponse" в api/basic/leaderboard в Promise<unknown> вместо unknown должна быть типизация

2024-06-26 14:38 UTC, ShamilSaifotdinov approved these changes

2024-06-26 16:44 UTC, ShamilSaifotdinov requested changes

2024-06-26 16:44 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Leaderboard/components/LeaderboardTable/index.tsx
> +          item.data.avatar !== undefined
У пользователя может не быть аватара

2024-06-27 02:47 UTC, kyzinatra approved these changes
Отличная работа! Особенно в вашей комманде мне нравится ваше ревью. Хорошая организация. Это очень важно и это, по моему мнению, один из главных факторов создания хорошей работы.
По поводу самой работы у меня вопросов нет. Изменений не так много и все они сделаны очень хорошо

2024-06-27 05:10 UTC, ShamilSaifotdinov approved these changes

2024-06-27 05:10 UTC, merged