STA-93 API для эмоджи (бекенд)
ShamilSaifotdinov/bugs-survivors pull request #56
Opened 2024-06-25 19:07 UTC by Aptyaa

### Какую задачу решаем
API для эмоджи (бекенд)

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-06-25 20:33 UTC, ShamilSaifotdinov requested changes

2024-06-25 20:33 UTC, ShamilSaifotdinov commented on packages/server/src/api/emoji.ts
> +  @validation(update_emoji)
Необходимо добавить валидацию на commentId (`@validation(<параметры проверки>, 'params')`)

2024-06-25 20:33 UTC, ShamilSaifotdinov commented on packages/server/src/models/emoji.ts
> +type EmojiRequest = Omit<IEmoji, 'id'>
Добавить отступ от экспорта класса

2024-06-25 20:33 UTC, ShamilSaifotdinov commented on packages/server/src/services/types.ts
> +  emoji?: IEmoji[] | null
IEmoji в данном случае не соответствует схеме:

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/332602be-7e07-4388-84ad-e07b7cf2aefc)

2024-06-25 20:33 UTC, ShamilSaifotdinov commented on packages/server/src/services/topic.ts
> -
Отступ оставить

2024-06-25 20:33 UTC, ShamilSaifotdinov commented on packages/server/src/services/emoji.ts
> +      attributes: ['emoji', [fn('count', col('emoji')), 'emoji_count']],
Не соответствует схеме (вместо count - emoji_count, count должен быть числом (сейчас строка)):

Сейчас:
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/c250e2e0-9e08-456a-baf8-758db8eacdbb)

Должно быть:
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/dd69aa41-314a-4647-8a56-ca4d58acdba2)

2024-06-26 18:25 UTC, ShamilSaifotdinov requested changes
Эти два catch не сочетаются друг с другом, из за чего происходит бесконечное ожидание

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/f69ac2e9-74ef-40a2-8e50-9f49f66c1d68)
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/35804a3a-fcd1-42b7-ab83-12f6172c0e3d)

2024-06-26 18:25 UTC, ShamilSaifotdinov commented on packages/server/src/api/emoji.ts
> +  public static update_emoji = async (req: Request, res: Response) => {
Необходимо в update_emoji присылать creator, так как у нас строгая связь с таблицей users
![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/44e7161d-71a0-4785-baaf-f7b2a19b7fdb)

2024-06-27 05:27 UTC, ShamilSaifotdinov approved these changes

2024-06-27 05:27 UTC, ShamilSaifotdinov commented on packages/server/src/services/emoji.ts
> +          creator,
creator можно не добавлять, достаточно creatorId

2024-06-27 06:34 UTC, kyzinatra commented on packages/server/src/api/emoji.ts
> +      }
Ошибки лучше вынести в отдельные константы

2024-06-27 06:34 UTC, kyzinatra commented on packages/server/src/models/emoji.ts
> +
Хорошая типизация

2024-06-28 18:07 UTC, Aptyaa commented on packages/server/src/api/emoji.ts
> +      }
Оставил обработку ошибку, в reason передаю ошибку, которую кидает emojiService

2024-06-29 09:18 UTC, ShamilSaifotdinov approved these changes

2024-06-29 12:53 UTC, merged