themes final
ShamilSaifotdinov/bugs-survivors pull request #71
Opened 2024-07-12 14:49 UTC by npb73

### Какую задачу решаем
Переключение тем клиентская часть 

### Скриншоты/видяшка (если есть)
![image](https://github.com/user-attachments/assets/e602c32a-0581-4ab5-92f3-c4d303580da1)
![image](https://github.com/user-attachments/assets/77dc1b9f-ce1f-41d0-8dd1-c9dd5633f4bb)

### TBD (если есть)

2024-07-12 15:20 UTC, ShamilSaifotdinov requested changes

2024-07-12 15:20 UTC, ShamilSaifotdinov commented on packages/client/src/pages/MainMenu/styles.module.scss
Лого менять не надо

2024-07-12 15:20 UTC, ShamilSaifotdinov commented on packages/client/src/main.tsx
Эти изменения не имеют смысла

2024-07-12 15:20 UTC, ShamilSaifotdinov commented on package-lock.json
package-lock.json здесь не должно быть

2024-07-13 17:19 UTC, ShamilSaifotdinov requested changes
Проверить отображения авторизации и регистрации. "Sign Up", "Sign In" и надписи лейблов не должны менять цвет

![image](https://github.com/user-attachments/assets/d4f2900f-1ba7-4554-be5e-4eb237631f2d)

---

Цвет светлых кнопок должен быть #F2F9F8, а не чисто белый

2024-07-13 17:19 UTC, ShamilSaifotdinov commented on packages/client/src/assets/scss/variables.scss
> +  --main-background: url('../../../public/images/main-menu_background.png');
Не нужно указывать относительный путь, возникаю предупреждения (должно быть как и раньше "/images/main-menu_background.png")

![image](https://github.com/user-attachments/assets/afce5dce-c9e4-47c9-9416-fd50f54f4c70)

2024-07-13 17:19 UTC, ShamilSaifotdinov commented on packages/client/src/assets/scss/variables.scss
> +  --main-background: url('../../../public/images/mainBackground.png');
Не нужно указывать относительный путь, возникаю предупреждения (должно быть как и раньше "/images/mainBackground.png")

![image](https://github.com/user-attachments/assets/afce5dce-c9e4-47c9-9416-fd50f54f4c70)

2024-07-13 20:14 UTC, ShamilSaifotdinov requested changes
Не видно логин в теме

![image](https://github.com/user-attachments/assets/809a09fa-c402-4069-adaf-c0532fdf29b7)

Исправить текст в результате игры
![image](https://github.com/user-attachments/assets/6102f431-da75-4043-905f-33f2e52c635b)

В форуме при темной теме вернуть текст и кнопки как раньше

2024-07-14 12:58 UTC, ShamilSaifotdinov requested changes
## Вход и регистрация:

Кнопки не соответствуют + кнопка входа должна быть прозрачная, пока пользователь не ввел данные:

Было:
![image](https://github.com/user-attachments/assets/bb15dc2d-5a45-44a7-8d6b-b9f61ca3f592)

Стало:
![image](https://github.com/user-attachments/assets/4cb3c325-5542-4489-8558-434386cdedb0)

## Профиль:

Было:

![image](https://github.com/user-attachments/assets/6ed7d647-27b9-448f-a5e1-aaf7184238a1)

Стало:

![image](https://github.com/user-attachments/assets/2980edbf-b3e4-48c7-99a0-a0d1b19d857a)

## Лидерборд и форум

Плохо читаемый текст (см текущую реализацию):

![image](https://github.com/user-attachments/assets/f8aa4850-0ccf-4118-9921-9fae72bd5b59)

![image](https://github.com/user-attachments/assets/6187fbc0-362e-43ce-be85-296c2ba72ad6)

2024-07-14 12:58 UTC, ShamilSaifotdinov commented on packages/client/src/hooks/useTheme.ts
> +      const response: ThemePostData = await setTheme({ theme: newTheme })
Нет смысла от этого присвоения - переменная нигде не используется

![image](https://github.com/user-attachments/assets/7c0fdd9c-0109-46c9-907b-9da2b646bd11)

2024-07-14 12:58 UTC, ShamilSaifotdinov approved these changes

2024-07-15 00:52 UTC, kyzinatra approved these changes
Отличная работа! Хорошая реализация переключения тем. Круто, что вы создаете data аттрибут на руте и привязываетесь к нему через `css`. Отличное решение! Также не в 1 раз отмечу очень внимательно ревью ваших коллег, которые очень внимательно прошлись по всему коду. 
Ваша работа принята! Желаю вам также успешно и в будущем писать ваши уже рабочие проекты! Было очень приятно проверять работы вашей комманды.

2024-07-15 22:15 UTC, closed without merging