STA-21 Вёрстка страницы форума
ShamilSaifotdinov/bugs-survivors pull request #8
Opened 2024-04-30 09:37 UTC by Lestrous

STA-21 Вёрстка страницы форума

Форум — страница, на которой пользователи могут создавать темы, оставлять в этих темах комментарии и отвечать на них. API вам предстоит написать самостоятельно в восьмом спринте.

Включает в себя задачи "STA-23 Сделать роут для страницы форума" и "STA-22 Сверстать экраны форума"

2024-04-30 20:28 UTC, ShamilSaifotdinov requested changes
Необходимо устранить ошибки теста

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/de4d5786-da56-4e42-81f7-33c95bb4a875)

2024-04-30 21:16 UTC, ShamilSaifotdinov requested changes

2024-04-30 21:16 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumSubjectTable/index.tsx
> +  { id: 'creator', label: 'CREATOR', align: 'center' },
Вместо "align: 'center'" лучше к заголовку добавить padding слева, чтобы было ровнее

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/265c8143-2e95-436e-a396-d9f947b944d3)

2024-04-30 21:16 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumSubjectTable/index.tsx
Не хватает кнопки "Create topic"

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/0cc47a02-8459-4078-ad6d-dbf6d71eaf31)

2024-04-30 21:16 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumTable/index.tsx
> +                  style={{
Стиль ячеек (строк) или сами ячейки (строки) лучше вынести как отдельный класс или компоненту

2024-04-30 21:16 UTC, ShamilSaifotdinov commented on packages/client/src/pages/Forum/components/ForumTopicTable/styles.module.scss
Должно выглядеть как лэндинг (у таблицы не должно быть скролла)

Как сейчас:

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/42a58214-b852-437e-a837-f911415644ab)

Должно быть:

![image](https://github.com/ShamilSaifotdinov/bugs-survivors/assets/63447562/650fac1d-7b64-470a-aa5c-e5fb1329b42c)

2024-05-01 10:21 UTC, Lestrous commented on packages/client/src/pages/Forum/components/ForumTopicTable/styles.module.scss
Исправления можно посмотреть на примере Технологии -> Tech 2

2024-05-01 14:05 UTC, ShamilSaifotdinov requested changes
Необходимо смержить main. Замечаний больше нет.

2024-05-01 15:02 UTC, kyzinatra commented on packages/client/src/pages/Forum/components/ForumSubjectTable/index.tsx
> +              .map(row => {
Можно лучше: довольно большая отрисовка. Можно использовать `useTransition()` и `useMemo()`

2024-05-01 15:04 UTC, kyzinatra commented on packages/client/src/pages/Forum/components/ForumTable/index.tsx
> +                <TableRow
По аналогии

2024-05-01 15:06 UTC, kyzinatra commented
Хорошая реализация. Из замечаний мог бы порекомендовать использовать `useMemo()` и `useTransition()` хуки для того, чтобы рендерить таблицы реже и более плавно, так как судя по всему они могут быть довольно большими. В остальном отличная работа!

2024-05-02 09:52 UTC, ShamilSaifotdinov approved these changes
👍

2024-05-02 09:53 UTC, merged